server:
  port: 8082

spring:
  profiles:
    default: dev

---

spring:
  config:
    activate:
      on-profile: dev
  datasource:
    driver-class-name: org.postgresql.Driver
    password: 3Yh5448i
    url: jdbc:postgresql://localhost:5432/dcbapp
    username: postgres
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

---


spring:
  config:
    activate:
      on-profile: qa
  datasource:
    driver-class-name: org.postgresql.Driver
    password: 3Yh5448i
    url: jdbc:postgresql://localhost:5432/dcbapp-qa
    username: postgres
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

---


spring:
  config:
    activate:
      on-profile: prod
  datasource:
    driver-class-name: org.postgresql.Driver
    password: 3Yh5448i
    url: jdbc:postgresql://localhost:5432/dcbapp-prod
    username: postgres
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
